# Generated by Django 4.2.10 on 2024-02-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_censorinfo_movieinfo_censor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movies.director'),
        ),
    ]
