# Generated by Django 4.2.10 on 2024-02-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_movieinfo_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='actors',
            new_name='actor',
        ),
    ]
