# Generated by Django 4.2.10 on 2024-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_actors_movieinfo_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='censor_details',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='censor_details',
            field=models.ManyToManyField(null=True, related_name='movie', to='movies.censorinfo'),
        ),
    ]
