# Generated by Django 4.2.10 on 2024-02-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movieinfo_censor_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='censor_details',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='censor_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.censorinfo'),
        ),
    ]
