# Generated by Django 4.2.10 on 2024-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movieinfo_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='movies.actor'),
        ),
    ]
