# Generated by Django 4.2.10 on 2024-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movieinfo_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='actor',
            field=models.ManyToManyField(to='movies.actor'),
        ),
    ]
